### PR TITLE
Added UNIX-like build support

### PR DESCRIPTION
**Pull request by Madotsukii**

### CODE REVIEW

**Comment by Madotsukii** [comment]
Was there something wrong with this?

**Comment by Alexander01998** [comment]
Yes. The "Windows only" restriction is on purpose. We don't want any Pull Requests from non-Windows users.

**Comment by Madotsukii** [comment]
Would you mind elaborating? Is it because of encoding on files like the minecraft.patch? Java is a cross-platform programming language so I figure it wouldn't be an issue. Are there windows-specific lines in wurst?

**Comment by MrDiamond123** [comment]
yo @Alexander01998 why no linux bro

**Pull request closed without merging**
